export SCREEN_WIDTH='1600'
export SCREEN_HEIGHT='1000'
export SCREEN_DEPTH='24'
export DISPLAY=':99.0'
export DBUS_SESSION_BUS_ADDRESS='/dev/null'
export GEOMETRY="$SCREEN_WIDTH""x""$SCREEN_HEIGHT""x""$SCREEN_DEPTH"